import {faker} from '@faker-js/faker'

const topType = [
	'NoHair',
	'Eyepatch',
	'Hat',
	'Hijab',
	'Turban',
	'WinterHat1',
	'WinterHat2',
	'WinterHat3',
	'WinterHat4',
	'LongHairBigHair',
	'LongHairBob',
	'LongHairBun',
	'LongHairCurly',
	'LongHairCurvy',
	'LongHairDreads',
	'LongHairFrida',
	'LongHairFro',
	'LongHairFroBand',
	'LongHairNotTooLong',
	'LongHairShavedSides',
	'LongHairMiaWallace',
	'LongHairStraight',
	'LongHairStraight2',
	'LongHairStraightStrand',
	'ShortHairDreads01',
	'ShortHairDreads02',
	'ShortHairFrizzle',
	'ShortHairShaggyMullet',
	'ShortHairShortCurly',
	'ShortHairShortFlat',
	'ShortHairShortRound',
	'ShortHairShortWaved',
	'ShortHairSides',
	'ShortHairTheCaesar',
	'ShortHairTheCaesarSidePart'
]
const accessoriesType = [
	'Blank',
	'Kurt',
	'Prescription01',
	'Prescription02',
	'Round',
	'Sunglasses',
	'Wayfarers'
]
const hairColor = [
	'Auburn',
	'Black',
	'Blonde',
	'BlondeGolden',
	'Brown',
	'BrownDark',
	'PastelPink',
	'Platinum',
	'Red',
	'SilverGray'
]
const facialHairType = [
	'Blank',
	'BeardMedium',
	'BeardLight',
	'BeardMajestic',
	'MoustacheFancy',
	'MoustacheMagnum'
]
const clotheType = [
	'BlazerShirt',
	'BlazerSweater',
	'CollarSweater',
	'GraphicShirt',
	'Hoodie',
	'Overall',
	'ShirtCrewNeck',
	'ShirtScoopNeck',
	'ShirtVNeck'
]
const eyeType = [
	'Close',
	'Cry',
	'Default',
	'Dizzy',
	'EyeRoll',
	'Happy',
	'Hearts',
	'Side',
	'Squint',
	'Surprised',
	'Wink',
	'WinkWacky'
]
const eyebrowType = [
	'Angry',
	'AngryNatural',
	'Default',
	'DefaultNatural',
	'FlatNatural',
	'RaisedExcited',
	'RaisedExcitedNatural',
	'SadConcerned',
	'SadConcernedNatural',
	'UnibrowNatural',
	'UpDown',
	'UpDownNatural'
]
const mouthType = [
	'Concerned',
	'Default',
	'Disbelief',
	'Eating',
	'Grimace',
	'Sad',
	'ScreamOpen',
	'Serious',
	'Smile',
	'Tongue',
	'Twinkle',
	'Vomit'
]
const skinColor = [
	'Tanned',
	'Yellow',
	'Pale',
	'Light',
	'Brown',
	'DarkBrown',
	'Black'
]

export const generateAvatar = () => {
	return `https://avataaars.io/?avatarStyle=Circle&topType=${faker.helpers.arrayElement(
		topType
	)}&accessoriesType=${faker.helpers.arrayElement(
		accessoriesType
	)}&hairColor=${faker.helpers.arrayElement(
		hairColor
	)}&facialHairType=${faker.helpers.arrayElement(
		facialHairType
	)}&clotheType=${faker.helpers.arrayElement(
		clotheType
	)}&eyeType=${faker.helpers.arrayElement(
		eyeType
	)}&eyebrowType=${faker.helpers.arrayElement(
		eyebrowType
	)}&mouthType=${faker.helpers.arrayElement(
		mouthType
	)}&skinColor=${faker.helpers.arrayElement(skinColor)}`
}
